allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  sharp: true
overrides:
  "@strapi/design-system": 2.2.2
patchedDependencies:
  '@strapi/design-system@2.2.2': patches/@strapi__design-system@2.2.2.patch
